### ISSUE TITLE
Rename THEMENAME in the *.info.yml file

### ISSUE THREAD

**Issue by tsega** [hussainweb/drupal-bootstrap-webpack#1]
In the `THEMENAME.starterkit.yml` file there is a reference to *THEMENAME*,

```
libraries-extend:
  bootstrap/framework:
    - THEMENAME/framework
```

It would be great if the `set-theme-name.sh` script could also change that along with the file names.

**Comment by hussainweb** [comment]
@tsega, the script already does this. Did you notice it not happening? Can you share the steps to reproduce this? I just tested it and it works well for me.

```bash
$ ./set-theme-name.sh test
$ cat test.info.yml
...
libraries-extend:
  bootstrap/framework:
    - test/framework
```

**Comment by tsega** [comment]
@hussainweb you are right, the script already handles that. I think I might have changed the name of the file manually before running the script. 😅 Closing this now.
